config/routes.rb
AiBrandawareness::Application.routes.draw do

  resources :sentiment_groups
  resources :brands do 
    get 'sentiments', :on => :member, :to => 'sentiments#index', :as => :sentiments
  end

  root :to => 'brands#new'
end

app/models/api.rb
require 'rest_client'
require 'json'

# Wraps basic get and post requests to rest servers
# Assumes response is in JSON
class API
  def self.get(path, options = {})
    params = options.merge(credentials).to_query
    begin
      response = RestClient.get("#{root}#{path}?#{params}")
      JSON.parse(response)
    rescue => e
      false
    end
  end

  def self.post(path, options = {})
    begin
      response = RestClient.post("#{root}#{path}", options.merge(credentials))
      JSON.parse(response)
    rescue => e
      false
    end
  end
end

app/models/brand.rb
class Brand < ActiveRecord::Base

  has_many :tweets
  has_many :sentiments
  has_many :keywords
  accepts_nested_attributes_for :keywords, :allow_destroy => true, :reject_if => proc { |attr| attr['value'].blank? }
  has_many :sentiment_group_members
  has_many :sentiment_groups, :through => :sentiment_group_members

  validates :name, :presence => { :message => 'Every brand needs a name' }
  validates :twitter_handle, :presence => { :message => 'Why are you here without a twitter handle?' },
            :uniqueness => { :message => 'That twitter handle is already in use' }
  
  before_save :initiate_state

  STATE_PROCESSING = 'processing'
  STATE_ANALYZING = 'analyzing'
  STATE_READY = 'ready'

  def self.by_twitter(handle)
    where(:twitter_handle => handle).first
  end

  # creates a new tweet record for every @new_tweets
  def add_tweets(new_tweets)
    new_tweets.each do |t|
      tweets << Tweet.new(
          :tweet_id => t['id_str'],
          :body => t['text'],
          :to_user_id => t['to_user_id'],
          :from_user_id => t['from_user_id'],
          :time => t['created_at']
        )
    end
  end

  # removes each tweet from the brand
  def remove_tweets(old_tweets)
    Tweet.delete_all(:id => old_tweets.collect { |t| t.id })
  end 

  # updates the state of the brand to start analyzing, 
  #as well as the max id of the last tweet call
  def finished_processing!(max_id = 0)
    self.update_attributes(:last_max_id => max_id, :state => Brand::STATE_ANALYZING)
  end

  # updates the state of the brand to ready
  def finished_analyzing!
    self.update_attributes(:state => Brand::STATE_READY)
  end

  private
  # default state is processing, make sure it is set
  def initiate_state
    if new_record?
      self.state = Brand::STATE_PROCESSING
    end
  end
end

app/models/brand_observer.rb
class BrandObserver < ActiveRecord::Observer
  def after_create(brand)
    # add the twitter handle to the message queue for future processing
    QueueMaster.fast_enqueue_fanout(QueueMaster::BRAND_EXCHANGE, brand.twitter_handle)
  end
end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
  belongs_to :brand

  validates :value, :presence => { :message => 'Keywords need values' }
end

app/models/queue_master.rb
require 'bunny'
require 'amqp'

class QueueMaster

  BRAND_EXCHANGE = 'brand_exchange'
  ANALYSIS_EXCHANGE = 'analysis_exchange'

  def self.host
    'localhost'
  end

  # bunny is good at fast synchronous queueing
  def self.fast_enqueue_fanout(exchange_name, message)
    Bunny.run { |c| c.exchange(exchange_name, :type => :fanout, :durable => true).publish(message, :persistent => true) }
  end
end

app/models/sentiment.rb
class Sentiment < ActiveRecord::Base
  belongs_to :brand

  validates :timestamp, :presence => true
#  validates_uniqueness_of :timestamp, :scaope => :brand_id
  validates :num_tweets, :presence => true
  validates :total_score, :presence => true
  validates :num_positive, :presence => true
  validates :num_negative, :presence => true
end

app/models/sentiment_group.rb
class SentimentGroup < ActiveRecord::Base
  has_many :sentiment_group_members
  has_many :brands, :through => :sentiment_group_members
  accepts_nested_attributes_for :brands, :allow_destroy => true
end

app/models/sentiment_group_member.rb
class SentimentGroupMember < ActiveRecord::Base
  belongs_to :sentiment_group
  belongs_to :brand
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base

  belongs_to :brand

  validates :body, :presence => { :message => 'Tweets need a body' }
  validates :tweet_id, :uniqueness => { :message => 'We already have that tweet. thanks!' }
end

app/models/twitter.rb
# wraps calls to the twitter apis
class Twitter < API

  def self.root
    'http://search.twitter.com'
  end

  def self.credentials
    {}
  end

  # makes a call to the twitter search api given a query search
  # returns a json parsed response
  def self.search(query, search_options)
    get '/search.json', search_options.merge({ :q => query, :include_entities => true })
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def make_error(obj)
    obj.errors.first.second
  end

  def make_response(status, message, other = {})
    { :status => status, :message => message }.merge(other)
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def index
    @brands = Brand.all
    # TODO: only pull actives? 
    # @brands = Brand.where(:active => true)
  end

  def show
    @brand = Brand.find(params[:id])
  end

  def new
    @brand = Brand.new
    @brand.keywords.build
  end

  def create
    @brand = Brand.new(params[:brand])
    if @brand.save
      response = { :status => 'success', :message => 'Brand added' }
    else
      response = { :status => 'error', :message => make_error(@brand) }
    end

    puts response.inspect
    respond_to do |format|
      format.html { redirect_to brands_path, :flash => { :notice => response } }
      format.js { render :json => response }
    end
  end

  def edit
    @brand = Brand.find(params[:id])
    @brand.keywords.build
  end

  def update
    @brand = Brand.find(params[:id])
    if @brand.update_attributes(params[:brand])
      response = { :status => 'success', :message => 'Brand updated' }
    else
      response = { :status => 'error', :message => make_error(@brand) }
    end

    respond_to do |format|
      format.html { redirect_to brands_path, :flash => { :notice => response } }
      format.js { render :json => response }
    end
  end

  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy
    # TODO: cleanup tweets or something
    redirect_to brands_path
  end

end

app/controllers/sentiment_groups_controller.rb
class SentimentGroupsController < ApplicationController
  def index
    @sentiment_groups = SentimentGroup.all
  end

  def show
    @sentiment_group = SentimentGroup.find(params[:id])
  end

  def new
    @sentiment_group = SentimentGroup.new
    @brands = Brand.all
  end

  def create
    @sentiment_group = SentimentGroup.new(params[:sentiment_group])
    if @sentiment_group.save
      redirect_to @sentiment_group, notice: make_response('success', 'Sentiment Group created successfully')
    else
      redirect_to new_sentiment_group_path, notice: make_response('error', make_error(@sentiment_group))
    end
  end

  def edit
    @sentiment_group = SentimentGroup.find(params[:id])
    @brands = Brand.all
  end

  def update
    @sentiment_group = SentimentGroup.find(params[:id])
    @sentiment_group.sentiment_group_members.destroy_all
    if @sentiment_group.update_attributes(params[:sentiment_group])
      redirect_to @sentiment_group, notice: make_response('success', 'Successfully updated Sentiment Group')
    else
      redirect_to edit_sentiment_group_path(@sentiment_group)
    end
  end

  def destroy
    @sentiment_group = SentimentGroup.find(params[:id])
    @sentiment_group.sentiment_group_members.destroy_all
    @sentiment_group.destroy
    redirect_to sentiment_groups_path, notice: make_response('success', 'Deleted Sentiment group')
  end

end

app/controllers/sentiments_controller.rb
class SentimentsController < ApplicationController
  def index
    @brand = Brand.find(params[:id])
    # TODO: over a given time period?
    @sentiments = @brand.sentiments
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/sentiment_groups_helper.rb
module SentimentGroupsHelper
end

app/helpers/sentiments_helper.rb
module SentimentsHelper
end

app/helpers/twitter_helper.rb
module TwitterHelper
  ACCOUNT_HANDLES = ['joeycarmello', 'gregguida']
  
  def twitter_random_first
    @rand ||= ACCOUNT_HANDLES.sort_by { rand }
    @rand.first
  end
  
  def twitter_random_second
    @rand ||= ACCOUNT_HANDLES.sort_by { rand }
    @rand.second
  end

end

app/views/brands/_form.html.erb
<%= form_for @brand do |f| %>
  <fieldset>
    <div class="clearfix">
      <%= f.label :name %>
      <div class="input">
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="clearfix">
      <%= f.label :twitter_handle, 'Twitter' %>
      <div class="input">
        <div class="input-prepend">
          <span class="add-on">@</span>
          <%= f.text_field :twitter_handle %>
        </div>
      </div>
    </div>
  </fieldset>
  <div id="keyword_section">
    <h3>Keywords <small>These will be treated as hashtags</small></h3>
    <ul class="unstyled tags">
      <%= f.fields_for :keywords do |keyword_form| %>
      <li>
        <%= keyword_form.text_field :value, :placeholder => 'New hashtag' %>
        <% unless @brand.new_record? %>
          <span>
          <%= keyword_form.check_box :_destroy %>
          Delete
          </span>
        <% end %> 
      </li>
      <% end %>
    </ul>
  </div>

  <div class="actions">
    <%= f.submit :class => 'btn primary' %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<div class="page-header">
  <h2>New Brand</h2>
</div>

<%= render 'form' %>

app/views/brands/index.html.erb
<div class="page-header">
  <h2>Brands</h2>
</div>

<%= link_to 'New Brand', new_brand_path, :class => 'btn' %>

<ul class="unstyled">
  <% @brands.each do |brand| %>
  <li><%= link_to brand.name, brand %></li>
  <% end %>
</ul>

app/views/brands/new.html.erb
<div class="page-header">
  <h2>New Brand</h2>
</div>

<%= render 'form' %>

app/views/brands/show.html.erb
<div class="page-header">
  <h2>Brand Page: <%= @brand.name %> <small><%= link_to 'edit', edit_brand_path(@brand) %></small></h2>
</div>

<p>
  Twitter Handle: <b>@<%= link_to @brand.twitter_handle, "http://twitter.com/#!/#{@brand.twitter_handle}", :target => '_blank' %></b>
</p>

<div id="keyword_section">
  <h3>Keywords</h3>
  <ul class="unstyled">
  <% @brand.keywords.each do |k| %>
    <li><%= k.value %></li>
  <% end %>
  </ul>
</div>

<%= link_to 'Sentiment Graph', sentiments_brand_path(@brand) %>

<h3>Recent Tweets</h3>
<ul id="recent_tweets" class="unstyled">
</ul>

<%= content_for :javascript_delay do %>
  <%= "<script src=\"http://twitter.com/statuses/user_timeline/#{@brand.twitter_handle}.json?callback=BRAND.show.load_tweets\"></script>".html_safe %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AI Research Project</title>
  <link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.3.0/bootstrap.min.css">
  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <div id="navigation">
    <span><%= link_to 'Brands', brands_path %></span>
    <span><%= link_to 'Sentiment Groups', sentiment_groups_path %></span>
  </div>
</header>

<div id="main">
<% if flash[:notice] %>
  <div class="alert-message <%= flash[:notice][:status] == 'success' ? 'success' : flash[:notice][:status] == 'error' ? 'error' : 'warning'  %>">
    <%= flash[:notice][:message] %>
  </div>
<% end %>
<% if flash[:error] %>
  <div class="alert-message error">
    <%= flash[:error][:message] %>
  </div>
<% end %>
<%= yield %>
</div>

<script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>
<%= javascript_include_tag "application" %>
<%= yield :javascript_delay %>
</body>
</html>

app/views/sentiment_groups/_form.html.erb
<%= form_for @sentiment_group do |f| %>

<fieldset>
  <div class="clearfix">
    <%= f.label :name %>
    <div class="input">
      <%= f.text_field :name %>
    </div>
  </div>
<div class="clearfix">
  <%= f.label :team_memberships, "Members" %>
  <div class="input">
    <%= select(:sentiment_group, :brand_ids, options_for_select(@brands.collect{ |b| [b.name, b.id ] }, 
               @sentiment_group.brands.collect {|b| b.id}), {}, {:multiple => true, :size => 6, :id => 'brand_chooser', :title => 'Select Brands'}) %>
  </div>
</div>
</fieldset>

<div class="actions">
  <%= f.submit 'Save', :class => 'btn primary' %>
</div>
<% end %>

<% content_for :javascript_delay do %>
<script>
$(document).ready(function() {
  $('#brand_chooser').asmSelect({highlight: true, animate: true});
});
</script>
<% end %>

app/views/sentiment_groups/edit.html.erb
<div class="page-header">
  <h2>Edit Sentiment Group</h2>
</div>

<%= render 'form' %>

app/views/sentiment_groups/index.html.erb
<div class="page-header">
  <h2>Sentiment Groups</h2>
</div>

<%= link_to 'New Group', new_sentiment_group_path, :class => 'btn' %>

<ul class="unstyled">
<% @sentiment_groups.each do |s| %>
  <li><%= link_to s.name, s %></li>
<% end %>
</ul>

app/views/sentiment_groups/new.html.erb
<div class="page-header">
  <h2>New Sentiment Group</h2>
</div>

<%= render 'form' %>

app/views/sentiment_groups/show.html.erb
<div class="page-header">
  <h2>Sentiment Group <small>Comparing <%= @sentiment_group.brands.collect{|b| b.name }.to_sentence %></small></h2>
  <div class="pull-right">
    <%= link_to 'Edit', edit_sentiment_group_path(@sentiment_group), :class => 'btn' %>
  </div>
</div>

<div id="sentiment_graph_target">
</div>

<% content_for :javascript_delay do %>
<script>
  var chart;
  Highcharts.setOptions({
    global: {
      useUTC: false 
    }
  });
  $(document).ready(function() {

    chart = new Highcharts.Chart({
      chart: {
        renderTo: 'sentiment_graph_target',
        zoomType: 'x',
        type: 'spline'
      },
      title: {
        text: 'Tweet Sentiments for <%= @sentiment_group.name %> over Time'
      },
      xAxis: {
        type: 'datetime',
        maxZoom: 36000000,
        dateTimeLabelFormats: {
          minute: '%I:%M%p',
          hour: '%I:%M%p',
          day: '%e. %b',
          week: '%e. %b',
          month: '%e. %b',
          year: '%b'
        }
      },
      yAxis: {
        title: {
          text: 'Tweet Sentiment (intensity)'
        },
        showFirstLabel: false
      },
      tooltip: {
        formatter: function() {
          return '<b>'+ this.series.name +': ' + this.y  + '</b><br/>' + Highcharts.dateFormat('%B %e %Y %I:%M%p', this.x);
        }
      },
      series: [
        <%= @sentiment_group.brands.collect {|brand| 
           "{
              name: '#{brand.name}',
              data: [ 
                #{brand.sentiments.where("timestamp > #{(Time.now - 1.day).to_i}").collect{ |s| "[#{s.timestamp * 1000},  #{(((s.num_positive - s.num_negative) / s.num_tweets.to_f) * 1000).floor / 100.0} ]" }.join(',') }
              ]
            }"
          }.join(',') %>
    ],
    plotOptions: {
         area: {
            lineWidth: 1,
            marker: {
               enabled: false,
               states: {
                  hover: {
                     enabled: true,
                     radius: 5
                  }
               }
            },
            shadow: false,
            states: {
               hover: {
                  lineWidth: 1                  
               }
            }
         }
      }
    });
  });
</script>
<% end %>

app/views/sentiments/index.html.erb
<div class="page-header">
  <h2>Sentiment Graph</h2>
</div>

<div id="sentiment_graph">
</div>

<% content_for :javascript_delay do %>
<script>
  var chart;
  Highcharts.setOptions({
    global: {
      useUTC: false 
    }
  });
  $(document).ready(function() {

    chart = new Highcharts.Chart({
      chart: {
        renderTo: 'sentiment_graph',
        zoomType: 'x',
        type: 'spline'
      },
      title: {
        text: 'Tweet Sentiments for <%= @brand.name.gsub(/'|"/, "\\\\'") %> over Time'
      },
      subtitle: {
         text: 'Search Terms <%= ([@brand.twitter_handle] | @brand.keywords.collect{|k| k.value }).to_sentence %>'
      },
      xAxis: {
        type: 'datetime',
        maxZoom: 3600000,
        dateTimeLabelFormats: {
          hour: '%I:%M%p',
          day: '%e. %b',
          week: '%e. %b',
          month: '%e. %b',
          year: '%b'
        }
      },
      yAxis: {
        title: {
          text: 'Tweet Sentiment (intensity)'
        },
        showFirstLabel: false
      },
      tooltip: {
        formatter: function() {
          return '<b>'+ this.series.name +': ' + this.y  + '</b><br/>' + Highcharts.dateFormat('%B %e %Y %I:%M%p', this.x);
        }
      },
      series: [
        {
          name: 'Average Intensity',
          data: [<%= @sentiments.collect{ |s| "[ #{s.timestamp * 1000}, #{( ((s.total_score.to_f / s.num_tweets) * 2000).floor) / 100.0 } ]" }.join(',') %>]
        }
      ],
    plotOptions: {
         area: {
            lineWidth: 1,
            marker: {
               enabled: false,
               states: {
                  hover: {
                     enabled: true,
                     radius: 5
                  }
               }
            },
            shadow: false,
            states: {
               hover: {
                  lineWidth: 1                  
               }
            }
         }
      }
    });
  });
</script>
<% end %>